export const resources = {
  orders: {
    model: 'order',
    permission: 'orders.read',
    search: ['orderNumber'],
    status: 'status',
    columns: ['orderNumber', 'status', 'total', 'paymentMethod', 'createdAt'],
    title: 'Orders',
  },
  products: {
    model: 'product',
    permission: 'products.read',
    search: ['name', 'slug', 'scientificName'],
    columns: ['name', 'price', 'stock', 'active', 'createdAt'],
    title: 'Products',
  },
  inventory: {
    model: 'product',
    permission: 'inventory.read',
    search: ['name', 'slug'],
    columns: ['name', 'stock', 'active', 'updatedAt'],
    title: 'Inventory',
  },
  categories: {
    model: 'category',
    permission: 'products.read',
    search: ['name'],
    columns: ['name', 'slug', 'active'],
    title: 'Categories',
  },
  gardeners: {
    model: 'gardener',
    permission: 'gardeners.read',
    search: ['name', 'city'],
    columns: ['name', 'city', 'verified', 'active', 'rating', 'jobsCompleted'],
    title: 'Gardeners',
  },
  bookings: {
    model: 'serviceBooking',
    permission: 'bookings.read',
    search: ['bookingNumber', 'customerName'],
    status: 'status',
    columns: ['bookingNumber', 'customerName', 'status', 'scheduledAt', 'price', 'rating'],
    title: 'Bookings',
  },
  services: {
    model: 'gardeningService',
    permission: 'services.read',
    search: ['title', 'category'],
    columns: ['title', 'category', 'price', 'durationMinutes', 'active'],
    title: 'Services',
  },
  payouts: {
    model: 'gardenerPayout',
    permission: 'finance.read',
    search: ['reference'],
    status: 'status',
    columns: ['bookingId', 'gross', 'platformFee', 'net', 'status', 'paidAt'],
    title: 'Gardener payouts',
  },
  plants: {
    model: 'gardenPlant',
    permission: 'plant-health.read',
    search: ['name', 'species', 'location'],
    status: 'lifecycleStatus',
    columns: ['name', 'species', 'environment', 'health', 'lifecycleStatus'],
    title: 'Plants',
  },
  ai: {
    model: 'aiConversation',
    permission: 'ai.read',
    search: ['title'],
    columns: ['title', 'userId', 'createdAt', 'updatedAt'],
    title: 'AI conversations',
  },
  'ai-feedback': {
    model: 'aiFeedback',
    permission: 'ai.feedback.read',
    search: ['note'],
    columns: ['helpful', 'reason', 'note', 'createdAt'],
    title: 'AI feedback',
  },
  recommendations: {
    model: 'plantRecommendation',
    permission: 'plant-health.read',
    search: [],
    status: 'status',
    columns: ['plantId', 'action', 'priority', 'status', 'createdAt'],
    title: 'Recommendations',
  },
  outcomes: {
    model: 'plantOutcomeRecord',
    permission: 'plant-health.read',
    search: ['reason'],
    columns: ['plantId', 'outcome', 'reason', 'recordedAt'],
    title: 'Plant outcomes',
  },
  ratings: {
    model: 'serviceBooking',
    permission: 'ratings.read',
    search: ['customerName', 'bookingNumber'],
    columns: ['bookingNumber', 'customerName', 'rating', 'issue', 'completedAt'],
    title: 'Gardener ratings',
  },
  support: {
    model: 'supportConversation',
    permission: 'support.read',
    search: ['subject'],
    status: 'status',
    columns: ['subject', 'userId', 'status', 'lastMessageAt'],
    title: 'Support tickets',
  },
  content: {
    model: 'banner',
    permission: 'content.read',
    search: ['title', 'placement'],
    columns: ['title', 'placement', 'active', 'sortOrder'],
    title: 'Banners & content',
  },
  notifications: {
    model: 'adminNotificationDraft',
    permission: 'notifications.read',
    search: ['title', 'message'],
    status: 'status',
    columns: ['title', 'userId', 'status', 'createdAt'],
    title: 'Notification drafts',
  },
  rewards: {
    model: 'rewardTransaction',
    permission: 'rewards.read',
    search: ['title'],
    columns: ['userId', 'points', 'type', 'title', 'createdAt'],
    title: 'Rewards ledger',
  },
  'admin-users': {
    model: 'adminStaff',
    permission: 'admin.manage',
    search: ['email'],
    columns: ['email', 'role', 'active', 'createdAt'],
    title: 'Admin users',
  },
  'audit-logs': {
    model: 'adminAuditLog',
    permission: 'audit.read',
    search: ['action', 'entity', 'reason'],
    columns: ['actorId', 'action', 'entity', 'reason', 'createdAt'],
    title: 'Audit history',
  },
} as const;
export type Resource = keyof typeof resources;
