ALTER TYPE "EvidenceSource" ADD VALUE IF NOT EXISTS 'USER_REPORTED';
ALTER TYPE "EvidenceSource" ADD VALUE IF NOT EXISTS 'SENSOR_DATA';
ALTER TYPE "AiFeedbackReason" ADD VALUE IF NOT EXISTS 'TOO_GENERIC';
ALTER TYPE "AiFeedbackReason" ADD VALUE IF NOT EXISTS 'DIDNT_WORK';
